# Schema for the configuration files of the royal_blocks module.
consum_social_networks_blocks.settings:
  type: config_object
  label: 'Consum Social Networks Settings'
  mapping:
    consum_socialnetworks:
      type: mapping
      label: 'Social Networks Settings'
      mapping:
        twitter_id:
          type: string
          label: 'Twitter ID'
        facebook_id:
          type: string
          label: 'Facebook ID'
        instagram_id:
          type: string
          label: 'Instagram ID'
        youtube_id:
          type: string
          label: 'Youtube ID'