version: "3"
# Rename this file to docker-compose.override.yml
# Use it to add any custom settings to docker-compose.override.yml
services:

  node:
    image: wodby/node:$NODE_TAG
    container_name: "${PROJECT_NAME}_node"
    working_dir: "${THEME_PATH}"
    labels:
      - "traefik.http.services.${PROJECT_NAME}_node.loadbalancer.server.port=3000"
      - "traefik.http.routers.${PROJECT_NAME}_node.rule=Host(`node.${PROJECT_BASE_URL}`)"
    expose:
      - "3000"
    volumes:
      - ../:/var/www/html
    # This command is used to keep the node container alive.
    command: tail -f /dev/null
