<?php

/**
 * @file
 * Contains drupal_migrate_party.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function royal_migrate_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the drupal_migrate_party module.
    case 'help.page.royal_migrate':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Este módulo se encarga de importar contenido desde el wordpress "Cuidarnos" de Consum.') . '</p>';
      return $output;

    default:
  }
}
