version: "3.5"

services:
  mariadb:
    image: wodby/mariadb:$MARIADB_TAG
    container_name: "${PROJECT_NAME}_mariadb"
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    expose:
      - "3306"
    networks:
      - backend
    volumes:
      - db_data:/var/lib/mysql

  solr:
    image: solr:8
    container_name: "${PROJECT_NAME}_solr"
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/var/solr
    command:
      - solr-precreate
      - gettingstarted
    networks:
      - backend

networks:
  backend:
    name: $NETWORK

volumes:
  db_data:
  solr_data: