enabled: consum
settings:
  redirect_url: ''
  client_id: MnntETD49LVpifiymFZcQG3js8Ia
  client_secret: JrN8urvA33_7n7LifV8PrTkStv0a
  authorization_endpoint: 'https://consum.docker.localhost:9443/oauth2/authorize'
  token_endpoint: 'https://172.10.0.10:9443/oauth2/token'
  userinfo_endpoint: 'https://172.10.0.10:9443/oauth2/userinfo'
  create_user_endpoint: 'https://172.10.0.10:9443/api/identity/user/v1.0/me'
  create_user_callback: 'https://consum.docker.localhost:9443/authenticationendpoint/login.do'
  cancel_user_endpoint: 'https://172.10.0.10:9443/scim2/Users'
  logout_user_endpoint: 'https://consum.docker.localhost:9443/oidc/logout'
  logout_redirect_uri: 'http://consum.docker.localhost/user/logout/success'
  claims_emailaddress_uri: 'http://wso2.org/claims/emailaddress'
  claims_identificationNumber_uri: 'http://wso2.org/claims/nickname'
  check_session_endpoint: 'https://consum.docker.localhost:9443/oidc/checksession'
  check_session_enable: 1
  iam_user: admin
  iam_password: admin
  guzzle_verify: 'false'
  guzzle_cert_path: ''
  debug_mode: 1
