varnish_flush_cron: null
varnish_version: '4'
varnish_control_terminal: 'varnish:6082'
varnish_control_key: secret
varnish_socket_timeout: '100'
varnish_cache_clear: '1'
varnish_bantype: '0'
varnish_cmdlength_limit: 7500
_core:
  default_config_hash: DxeHlEyOM-znvcRf6mmkhXwywgcKl2f-tvbALo_EtcE
langcode: es
