<?php

/**
 * Implements hook_theme().
 */
function consum_custom_blocks_theme() {
  return [
    'consum_customtext' => [
      'variables' => [
        'text1' => NULL,
        'height' => NULL,
        'customHeight' => NULL,
        'customStyle' => NULL,
        'background_color' => NULL,
        'visibility' => NULL,
        'hide' => NULL
      ],
      'template' => 'block--consum-customtext-block',
    ],
    
    'consum_content_carousel_taxonomy' => [
      'variables' => [
        'terms' => NULL,
      ],
      'template' => 'block--consum-carousel-taxonomy-block',
    ],
    'content_cabecera_breadcrumb' => [
      'variables' => [
        'listLinks' => NULL
      ],
      'template' => 'block--consum-cabecera-breadcrumb-block',
    ],
    'content_carousel_unlimited' => [
      'variables' => [
        'num_items' => NULL,
        'visibility' => NULL,
        'items' => NULL,
        'height' => NULL,
        'customHeight' => NULL,
        'customStyle' => NULL,
        'background_color' => NULL,
        'visibility' => NULL,
        'hide' => NULL
      ],
      'template' => 'block--consum-carousel-unlimited-block',
    ]
  ];
}