<?php

/**
 * @file
 * Contains consum_fields.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function consum_fields_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the consum_fields module.
    case 'help.page.consum_fields':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module for fields plugins') . '</p>';
      return $output;

    default:
  }
}
