<?php

/**
 * Implements hook_theme().
 */
function consum_comunidad_theme()
{
  return array(
    'content_community_navigation' => array(
      'template' => 'block--community_navigation-block',
    ),
    'content_community_profile' => array(
      'variables' => array(
        'user' => NULL,
      ),
      'template' => 'block--community_profile-block',
    ),
  );
}

/**
 * Implements hook_preprocess_image_widget().
 */
function consum_comunidad_preprocess_image_widget(&$variables)
{
  $element = $variables['element'];

  $variables['attributes'] = array('class' => array('image-widget', 'js-form-managed-file', 'form-managed-file', 'clearfix'));

  if (!empty($element['fids']['#value'])) {
    $file = reset($element['#files']);
    $element['file_' . $file->id()]['filename']['#suffix'] = ' <span class="file-size">(' . format_size($file->getSize()) . ')</span> ';
    $file_variables = array(
      'style_name' => $element['#preview_image_style'],
      'uri' => $file->getFileUri(),
    );

    // Determine image dimensions.
    if (isset($element['#value']['width']) && isset($element['#value']['height'])) {
      $file_variables['width'] = $element['#value']['width'];
      $file_variables['height'] = $element['#value']['height'];
    } else {
      $image = \Drupal::service('image.factory')->get($file->getFileUri());
      if ($image->isValid()) {
        $file_variables['width'] = $image->getWidth();
        $file_variables['height'] = $image->getHeight();
      } else {
        $file_variables['width'] = $file_variables['height'] = NULL;
      }
    }

    $element['preview'] = array(
      '#weight' => -10,
      '#theme' => 'image_style',
      '#width' => $file_variables['width'],
      '#height' => $file_variables['height'],
      '#style_name' => $file_variables['style_name'],
      '#uri' => $file_variables['uri'],
    );

    // Store the dimensions in the form so the file doesn't have to be
    // accessed again. This is important for remote files.
    $element['width'] = array(
      '#type' => 'hidden',
      '#value' => $file_variables['width'],
    );
    $element['height'] = array(
      '#type' => 'hidden',
      '#value' => $file_variables['height'],
    );
  }

  $variables['data'] = array();
  foreach (\Drupal\Core\Render\Element::children($element) as $child) {
    $variables['data'][$child] = $element[$child];
  }
}

function consum_comunidad_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id){
  $account = Drupal\user\Entity\User::load(\Drupal::currentUser()->id());
  if (isset($form["#webform_id"])){
    if($form["#webform_id"] == "profile"){
      for ($i = 0; $i < count($account->get("field_intereses")->referencedEntities()); $i++){
        $interests[] = $account->get("field_intereses")[$i]->target_id;
      }
      $form['elements']['row_1']['avatar']['#theme'] = 'image_widget';
      $form['elements']['row_1']['avatar']['#preview_image_style'] = 'large';
      $form['elements']['row_1']['avatar']['#default_value'] = [
        'fid' => $account->get("user_picture")->target_id,
      ];
      $form['elements']['row_1']['nombre_del_usuario']['#default_value'] = $account->get("field_nombre")->value;
      $form['elements']['row_2']['sobre_mi']['#default_value'] = $account->get("field_sobre_mi")->value;
      $form['elements']['row_3']['intereses']['#default_value'] = $interests;
      $form['elements']['row_4']['row_4_1']['perfil_de_facebook']['#default_value'] = $account->get("field_perfil_de_facebook")->value;
      if ($account->get("field_ver_perfil_de_facebook")->value == 1){
        $form['elements']['row_4']['row_4_1']['ver_perfil_facebook']['#default_value'] = array("1");
      }
      $form['elements']['row_4']['row_4_2']['perfil_de_twitter']['#default_value'] = $account->get("field_perfil_de_twitter")->value;
      if ($account->get("field_ver_perfil_de_twitter")->value == 1){
        $form['elements']['row_4']['row_4_2']['ver_perfil_twitter']['#default_value'] = array("1");
      }
      $form['elements']['row_4']['row_4_3']['perfil_de_instagram']['#default_value'] = $account->get("field_perfil_de_instagram")->value;
      if ($account->get("field_ver_perfil_de_instagram")->value == 1){
        $form['elements']['row_4']['row_4_3']['ver_perfil_instagram']['#default_value'] = array("1");
      }
      if ($account->get("field_notificacion_comentario_mi")->value == 1){
        $form['elements']['row_5']['notificacion_receta']['#default_value'] = array("1");
      }
      if ($account->get("field_notificacion_email_amigo")->value == 1){
        $form['elements']['row_5']['notificacion_amigo']['#default_value'] = array("1");
      }
    }
  }
}

function consum_comunidad_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'consum_comunidad/consum_comunidad';
}