<?php

/**
 * @file
 * Contains housework_organizer.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function housework_organizer_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the consum_organizator module.
    case 'help.page.housework_organizer':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('HouseWork Organizer') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function housework_organizer_theme() {
  return [
    'housework_organizer' => [
      'variables' => [
        ],
        'template' => 'housework-organizer',
    ],
  ];
}
