<?php

/**
 * Implements hook_theme().
 */
function consum_cta_blocks_theme() {
  return [
    'consum_cta' => [
      'variables' => [
        'img1' => NULL,
        'gradient' => NULL,
        'img2' => NULL,
        'text1' => NULL,
        'text2' => NULL,
        'height' => NULL,
        'customHeight' => NULL,
        'customStyle' => NULL,
        'link' => NULL,
        'button_color' => NULL,
        'background_color' => NULL,
        'target' => NULL,
        'visibility' => NULL,
        'hide' => NULL,
        'autocomplete' => NULL
      ],
      'template' => 'block--consum-cta-block',
    ],
    'consum_cta2' => [
      'variables' => [
        'img1' => NULL,
        'gradient' => NULL,
        'img2' => NULL,
        'text1' => NULL,
        'text2' => NULL,
        'height' => NULL,
        'customHeight' => NULL,
        'customStyle' => NULL,
        'link' => NULL,
        'button_color' => NULL,
        'background_color' => NULL,
        'target' => NULL,
        'visibility' => NULL,
        'hide' => NULL,
        'autocomplete' => NULL,
        'icon' => NULL,
        'texto_enlace' => NULL,
        'maquetacion' => NULL,
        'posicion_btn' => NULL,
        'alineacion_icon' => NULL
      ],
      'template' => 'block--consum-cta2-block',
    ],
    'consum_popup_custom' => [
      'variables' => [
        'img1' => NULL,
        'gradient' => NULL,
        'text1' => NULL,
        'text2' => NULL,
        'height' => NULL,
        'customHeight' => NULL,
        'customStyle' => NULL,
        'link' => NULL,
        'button_color' => NULL,
        'background_color' => NULL,
        'target' => NULL,
        'visibility' => NULL,
        'hide' => NULL,
        'autocomplete' => NULL,
        'modal_text' => NULL
      ],
      'template' => 'block--consum-popup-custom-block',
    ],
    'content_consum-imagenhover' => [
      'variables' => [
        'img1' => NULL,
        'gradient' => NULL,
        'img2' => NULL,
        'text1' => NULL,
        'text2' => NULL,
        'height' => NULL,
        'customHeight' => NULL,
        'customStyle' => NULL,
        'link' => NULL,
        'background_color' => NULL,
        'target' => NULL,
        'visibility' => NULL,
        'hide' => NULL,
        'autocomplete' => NULL
      ],
      'template' => 'block--consum-imagenhover-block',
    ],
  ];
}