<?php

/**
 * @file
 * Contains simple_ldap_role.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function simple_ldap_role_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name === 'help.page.simple_ldap_role') {
    $output = '';
    $output .= '<h3>' . t('About') . '</h3>';
    $output .= '<p>' . t('Simple LDAP role authorization.') . '</p>';
    return $output;
  }
}
