<?php

/**
 * @file
 * Contains consum_like_favorites.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Impl]ements hook_help().
 */
function consum_like_favorites_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the consum_like_favorites module.
    case 'help.page.consum_like_favorites':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Adds favorites and likes fields') . '</p>';
      return $output;

    default:
  }
}

/**
* Implements hook_preprocess_HOOK() for node.
*/
function consum_like_favorites_preprocess_node(&$variables) {
  $user_storage = \Drupal::service('entity_type.manager')->getStorage('user');
  $user = $user_storage->load($variables['user']->id());
  $variables['field_favorites'] = $user->get('field_favorites');
}