<?php

/**
 * Implements hook_theme().
 */
function consum_theme_blocks_theme() {
  return [
    'consum_theme_user' => array(
      'variables' => array(
        'user_picture' => NULL,
        'user_login' => NULL,
        'user_mundo_consum' => NULL,
        'btn_iam_login' => NULL,
      ),
      'template' => 'block--theme-user-block',
    ),
    'consum_theme_logo' => array(
      'template' => 'block--theme-logo-block',
    ),
    'consum_theme_btnHamburguesa' => array(
      'template' => 'block--theme-btnHamburguesa-block',
    ),
    'consum_theme_localizacion' => array(
      'template' => 'block--theme-localizacion-block',
    ),
    'consum_theme_politicasCopyright' => array(
      'template' => 'block--theme-politicasCopyright-block',
    ),
    'consum_theme_newsletterRrss' => array(
      'template' => 'block--theme-newsletterRrss-block',
    ),
    'consum_theme_horarioAtcC' => array(
      'template' => 'block--theme-horarioAtcC-block',
    ),
    'consum_theme_iconsAppAtcC' => array(
      'template' => 'block--theme-iconsAppAtcC-block',
    ),
    'consum_theme_iconSearch' => array(
      'template' => 'block--theme-iconSearch-block',
    ),
    'consum_theme_sectionPrev' => array(
      'variables' => array(
        'enlace' => NULL,
        'target' => NULL,
        'position' => NULL,
      ),
      'template' => 'block--theme-sectionPrev-block',
    ),
  ];
}

function consum_theme_blocks_block_view_alter(array &$build, \Drupal\Core\Block\BlockPluginInterface $block) {
  switch ($block->getBaseId()) {
    case 'page_title_block':
      $build['#attributes']['class'][] = 'col';
      $build['#attributes']['class'][] = 'd-none';
      $build['#attributes']['class'][] = 'd-sm-flex';
      $build['#attributes']['class'][] = 'order-sm-3';
      $build['#attributes']['class'][] = 'align-items-center';
      break;
    case 'search_form_block':
      $build['#attributes']['class'][] = 'd-none';
      $build['#attributes']['class'][] = 'd-sm-none';
      $build['#attributes']['class'][] = 'col-md';
      $build['#attributes']['class'][] = 'order-md-4';
      $build['#attributes']['class'][] = 'd-md-flex';
      $build['#attributes']['class'][] = 'justify-content-start';
      $build['#attributes']['class'][] = 'align-items-center';
      break;
    case 'system_menu_block':
      if ($block->getPluginId() == "system_menu_block:main"){
        if ($build['#block']->getRegion() == "sidebar"){
          $build['#attributes']['class'][] = 'col-12';
          $build['#attributes']['class'][] = 'col-sm-12';
          $build['#attributes']['class'][] = 'col-md-12';
          $build['#attributes']['class'][] = 'col-lg-12';
        }else if ($build['#block']->getRegion() == "navbar_principal"){
          $build['#attributes']['class'][] = 'col-auto';
          $build['#attributes']['class'][] = 'col-sm-auto';
          $build['#attributes']['class'][] = 'col-md-auto';
          $build['#attributes']['class'][] = 'col-lg-auto';
          $build['#attributes']['class'][] = 'order-3';
          $build['#attributes']['class'][] = 'd-none';
          $build['#attributes']['class'][] = 'd-sm-flex';
          $build['#attributes']['class'][] = 'block--title-categoria';
        }else if ($build['#block']->getRegion() == "menu_personalizado"){
          $build['#attributes']['class'][] = 'col-12';
          $build['#attributes']['class'][] = 'col-sm-12';
          $build['#attributes']['class'][] = 'col-md-3';
          $build['#attributes']['class'][] = 'col-lg-2';
          $build['#attributes']['class'][] = 'd-none';
          $build['#attributes']['class'][] = 'd-sm-flex';
          if (($build['#block']->get('id') == "submenu_secciones") && ($build['#block']->getRegion() == "menu_personalizado")){
            $build['#attributes']['class'][] = 'submenu3';
            $build['#attributes']['class'][] = 'submenu-hover-disabled';
          }
          if (($build['#block']->get('id') == "menu_secciones") && ($build['#block']->getRegion() == "menu_personalizado")){
            $build['#attributes']['class'][] = 'submenu2';
          }
        }
      }else{
        if ($block->getPluginId() == "system_menu_block:menu-accesibilidad"){
          $build['#attributes']['class'][] = 'col-12';
          $build['#attributes']['class'][] = 'col-sm-auto';
          $build['#attributes']['class'][] = 'col-md-auto';
          $build['#attributes']['class'][] = 'col-lg-auto';
        }else{
          $build['#attributes']['class'][] = 'col-12';
          $build['#attributes']['class'][] = 'col-sm-12';
          $build['#attributes']['class'][] = 'col-md-3';
          $build['#attributes']['class'][] = 'col-lg-2';
        }
      }
      break;
    case 'language_block':
      $build['#attributes']['class'][] = 'order-12';
      break;
    case 'logo_block':
      if ($build['#block']->getRegion() == "navbar_principal"){
        $build['#attributes']['class'][] = 'col-4';
        $build['#attributes']['class'][] = 'col-sm-auto';
        $build['#attributes']['class'][] = 'order-3';
        $build['#attributes']['class'][] = 'order-sm-1';
        $build['#attributes']['class'][] = 'd-flex';
        $build['#attributes']['class'][] = 'justify-content-center';
      }
    break;
  }
}

function consum_theme_blocks_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'consum_theme_blocks/global';
}

function consum_theme_blocks_preprocess_node(&$variables) {
  $variables['viajes_relacionados'] = views_embed_view('viajes_relacionados', 'block_1');
}