# Generated by Django 3.1.6 on 2021-02-12 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_category_post_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
