# Generated by Django 3.1.6 on 2021-02-15 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210212_0949'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
